#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	# If capacity is set, expands to x;
	# otherwise, expands to empty string.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	status=$(cat "$battery/status")
	capacity=$(cat "$battery/capacity")
	# Will make a warn variable if discharging and low
	[ "$status" = "Discharging" ] && [ "$capacity" -le 25 ] && warn="‼️"
	# Prints the info
	printf '%s%s%d%%\n' "Battery: " "$warn" "$capacity"; unset warn
done && exit 0
