#!/bin/sh
#    c    Weather condition,
#    C    Weather condition textual name,
#    x    Weather condition, plain-text symbol,
#    h    Humidity,
#    t    Temperature (Actual),
#    f    Temperature (Feels Like),
#    w    Wind,
#    l    Location,
#    m    Moon phase,
#    M    Moon day,
#    p    Precipitation (mm/3 hours),
#    P    Pressure (hPa),
#    u    UV index (1-12),
location="waterloo+ontario"
component="+%C+%t+%h+%p+%s\n"
curl -sf wttr.in/$location\?format="$component" | sed 's/^ //;s/:[0-9]*$//'
